nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
    "@typescript-eslint/parser@*":
        dependencies:
            "typescript": "*"
    "eslint-module-utils@*":
        dependencies:
            "typescript": "*"
    "@typescript-eslint/typescript-estree@*":
        dependencies:
            "typescript": "*"
